run-name: Build Test Publish
on: 
  pull_request:
    branches:
      - main

jobs:
  build-lib:
    name: Build Test lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build lib
        run: cargo build
      - name: Test lib
        run: cargo test
